### PR TITLE
add image support

### PR DESCRIPTION
**Pull request by richardanaya**
Adding basic image support.

I'm feeling like `Frame`  should be called `Surface`.

### CODE REVIEW

**Comment by nbrr** [comment]
> I'm feeling like `Frame` should be called `Surface`.

How about `Canvas`?

I think we'd want to advance on #9 before we start drawing actual stuff.

**Comment by richardanaya** [comment]
Canvas sounds good to m, one thing I observed is that pixel drawing is slow. I'm wondering how we'll be able to address that in layers.

**Comment by nbrr** [comment]
> Canvas sounds good to m, one thing I observed is that pixel drawing is slow. I'm wondering how we'll be able to address that in layers.

How slow? At what point did it become slow? I am working on layers and the drag example and it is indeed very slow, it wasn't the case before.

**Comment by richardanaya** [comment]
I was actually referring to drawing canvases on canvas in particular with `draw_canvas`

at one point I was just for looping over each pixel and copying the pixel from the image to the canvas' pixels and it was slow

I switched over to using `copy_from_slice` to copy pixels and it became an order of magnitude faster.

hmm, i'm not exactly how drag could have changed .. i'll check it the example on my phone!

**Comment by nbrr** [comment]
It didn't affect drag, my attempt at layers did, so I wanted to know whether we might have ran into the same issue. And we did, I run into troubles when I try to for loop on the pixels to clear the screen. I'm not sure how to get rid of the issue though.

**Pull request merged**
